#!/usr/bin/bash

invalidonly="no"

while getopts "i" opt; do
  case $opt in
    i)
      invalidonly="yes"
      ;;
    \?)
      echo "Error: Invalid option -$OPTARG" >&2
      echo "Usage: $0 [-n]" >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))

filelist=("$@")
infile="${filelist[0]}"

if [[ -z ${infile} ]];then 
	echo
	echo "You must supply a file name or expression (wildcards OK). Counts MARC tags in binary MARC files."
	echo "Usage: marcfc [filename]"
	echo 
	echo "Options:"
	echo "-i Invalid tags. Show only tags containing nonnumeric characters or subfields that are not numerals or lowercase letters"
	exit
fi

read -r -d '' awkscript << "ENDOFAWK"
#!/usr/bin/awk -f 

BEGIN { records_found = 0 }

function extract_subfields() { 
	field_length = substr(directory, i + 3, 4) + 0
	starting_pos = substr(directory, i + 7, 5) 
	field_content = ""
	delete subfields

	field_content = substr(record_content, starting_pos + 3, field_length - 3)

	if (substr(field_content, 1, 1) == SFS) {
		split(field_content, subfields, SFS)
		for (subfield_index in subfields) { 
			subfield = substr(subfields[subfield_index], 1, 1)
			tagcount[marctag""subfield]++ 
		}	
	} else {
		tagcount[marctag]++ 
	}
}


{
        if(length("а") != 2) {
                badawk = 1
                printf("Your version of awk does not support marcfc -- you need a version that supports the -b switch\\n")
                exit
        }

	leader=substr($0,1,24)
	baseaddress=substr(leader,13, 5) + 0
	directory=substr($0,25, baseaddress - 25)
	directory_length=length(directory) 
	directory_check=(directory_length % 12)
	record_content=substr($0, baseaddress + 1)
	
	for (i=1; i<=directory_length; i=i+12) {
		marctag = substr(directory, i, 3)
		extract_subfields()
	}
	
	if (NR % 1000 == 0){ printf "Records searched: "NR"\r", foundrecs }
}
END {
	print NR" records were searched"
	n = asorti(tagcount, sorted_bytag)

	print "Total records: "NR"\\n" > OUTFILE

	for (tag=1; tag<=n; tag++) {
		key = sorted_bytag[tag]

		if (INVALID == "yes") {
			if ((key ~ /[^0-9]/ && length(key) == 3) || (substr(key,4,1) !~ /[0-9a-z]/ && length(key) == 4)) {
				print key ":", tagcount[key] > OUTFILE
			} 
		} else {
			print key ":", tagcount[key] > OUTFILE
		}
	}
}

ENDOFAWK

echo -e "${awkscript}" > tmp_checkmarc
chmod 700 tmp_checkmarc

for file in "${filelist[@]}";do
	fileroot=$(echo "${file}" | sed 's/\.....\?$//')
	outfile="${fileroot}_fieldcounts.txt"
	awk -v RS=$'\x1d' -v ORS=$'\n' -v FS=$'\x1e' -v OFS="\t" -v SFS=$'\x1f' -v INVALID=${invalidonly} -v OUTFILE="${outfile}" -b -f tmp_checkmarc "${file}"
	echo "Field counts exported to ${outfile}"
	[[ ${invalidonly}=="yes" ]] && echo "Only invalid tags were exported"
	echo
done
echo
#rm -f tmp_checkmarc
