#!/usr/bin/bash

numfiles=""
num_per_file=10000

while getopts ":f:" opt; do
    case "$opt" in
        f)
            numfiles="$OPTARG"
            ;;
        *)
            echo "Usage: marcsplit [-f num_files] filename [num_records]"
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

infile="${1}"
[[ -z "${infile} ]] && {
    echo "Usage: marcsplit [-f num_files] filename [num_records]"
    exit 1
}

if [[ -n $numfiles ]]; then
    numrecs=$(awk -v RS=$'\x1d' 'END{print NR}' "$infile")
    num_per_file=$(( numrecs / numfiles + 1 ))
else
    [[ -n $2 ]] && num_per_file=$2
fi

read -r -d '' awkscript << "ENDOFAWK"
#!/usr/bin/awk -f 

BEGIN { filecounter = 1 } 
{
if (NR % NUMRECS == 0) {filecounter = filecounter + 1}
outfile = sprintf("m_split-%05d.mrc", filecounter)


print $0 > outfile
if (NR % 10000 == 0){ printf "Records procesessed: "NR"\r"}

}

ENDOFAWK

echo -e "${awkscript}" > tmp_awk_marcsplit
chmod 700 tmp_awk_marcsplit

awk -v RS=$'\x1d' -v ORS=$'\x1d' -v FS=$'\x1e' -v NUMRECS=$num_per_file -b -f tmp_awk_marcsplit "${infile}"
echo
numfiles=$(ls m_split* |wc -l)
echo "All records are processed into the following $numfiles files"
ls m_split*
echo
rm tmp_awk_marcsplit
