#!/usr/bin/bash
infile="${1}"
from=$2
to=$3

if [[ -z $from ]];then
   echo "Usage: marcslice [filename] [startrecord] [endrecord]"
   exit
fi

[[ -z $to ]] && to=99999999

awk -v RS=$'\x1d' -v ORS=$'\x1d' -v FROM=${from} -v TO=${to} '{if (NR >= FROM && NR <= TO){print $0}else{if (NR > TO){exit}}}' "${infile}" 


